export const siteConfig = {
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://q.dog",
  title: "QDog",
  altNames: [
    "QDog Cyber Life",
    "QDog 赛博生命",
    "Codex Pet Gallery",
    "Codex 宠物画廊",
    "Codex 精品宠物",
    "Codex 小宠物",
    "Codex Pets Community",
    "Codex Pet Store",
    "Codex 宠物商店",
  ],
  description:
    "Claim a free genome egg, hatch a persistent AI Cyber Life with 10 starter credits, and later bring the same identity into Codex.",
  descriptionZh:
    "免费领取基因蛋，用新账户赠送的 10 个积分孵化拥有永久身份的 AI 赛博生命，未来再让同一个生命进入 Codex。",
  shortDescription:
    "Hatch a persistent AI Cyber Life and bring it into Codex.",
  shortDescriptionZh:
    "孵化拥有永久基因身份的 AI 赛博生命，并让它进入 Codex。",
  ogImage: "/assets/cover/qdog-cover.png",
  ogImageWidth: 1659,
  ogImageHeight: 948,
  repo: "https://github.com/burgleaf/qdog-community",
  catalog: "/pets.json",
  collectionsCatalog: "/collections.json",
  requestsCatalog: "/requests.json",
  qdogServerApi: process.env.NEXT_PUBLIC_QDOG_SERVER_API ?? "https://api.q.dog",
  keywords: [
    "Cyber Life",
    "AI virtual pet",
    "AI companion",
    "genome pet egg",
    "赛博生命",
    "AI 宠物",
    "AI 伙伴",
    "宠物蛋孵化",
    "Codex",
    "Codex pet",
    "Codex pets",
    "custom Codex pet",
    "Codex custom pets",
    "install Codex pet",
    "how to install Codex pet",
    "Codex pet gallery",
    "Codex pets gallery",
    "Codex pets library",
    "Codex pet store",
    "free Codex pets",
    "Codex pet download",
    "download Codex pet",
    "request Codex pet",
    "free Codex pet request",
    "community Codex pet request",
    "Codex pet share",
    "Codex pet skill",
    "Codex Hatch Pet",
    "Hatch Pet skill",
    "create Codex pet",
    "Codex pet V1",
    "Codex pet V2",
    "Codex desktop companion",
    "OpenAI Codex",
    "desktop pet",
    "pixel art pet",
    "anime Codex pet",
    "game character Codex pet",
    "spritesheet",
    "Codex 宠物",
    "Codex 小宠物",
    "Codex 精品宠物",
    "Codex 宠物网站",
    "Codex 宠物社区",
    "Codex 宠物市场",
    "Codex 小宠物商店",
    "免费 Codex 宠物",
    "Codex 宠物下载",
    "Codex 宠物安装",
    "Codex 宠物制作申请",
    "免费申请 Codex 小宠物",
    "请社区制作 Codex 宠物",
    "Codex 宠物制作",
    "Codex 宠物自定义",
    "Codex 小宠物制作",
    "Codex 宠物 skill",
    "open source pet",
    "QDog",
  ],
};

export type SiteConfig = typeof siteConfig;
